spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  application:
    name: aiot-api
  datasource:
    url: jdbc:mariadb://27.102.205.67:3306/a_iot_new
    username: a_iot_new
    password: pluxity123!@#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

file:
  storage-strategy: s3
  local:
    path: C:/Dev/Upload/
  s3:
    endpoint-url: ${S3_ENDPOINT_URL:http://192.168.4.8:9000}
    public-url: ${S3_PUBLIC_URL:http://192.168.4.8:9000}
    bucket: aiot-bucket
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity0304
    pre-signed-url-expiration: 600

logging:
  level:
    com: DEBUG