spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/aiot
    username: pluxity
    password: pluxity0304
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

domain:
  url: ${API_URL:http://localhost:8080}

influx:
  url: http://dev.pluxity.com:8086
  token: kg04O5mxWTYM--k28CKYgNChc4pv0C3s1yx1VuUjp7kxoyzQDtkeT6M22af2A6RwXRAdbpEucV2GTqXN_iYlGQ==
  org: pluxity
  bucket: aiot-bucket

mediamtx:
  api-url: ${MEDIAMTX_API_URL:http://192.168.4.8:9997}
  view-url: ${MEDIAMTX_VIEW_URL:http://192.168.4.8:8889}

file:
  storage-strategy: s3
  local:
    path: C:/Dev/Upload/
  s3:
#    endpoint-url: http://127.0.0.1:9000
    endpoint-url: ${S3_ENDPOINT_URL:http://192.168.4.8:9000}
    public-url: ${S3_PUBLIC_URL:http://192.168.4.8:9000}
    bucket: aiot-bucket
    region: ap-northeast-2
    access-key: pluxity
    secret-key: pluxity0304
    pre-signed-url-expiration: 600

logging:
  level:
    com: DEBUG